import RightSidebar from '../components/RightSideBar'
import Sidebar from '../components/Sidebar'
import NavBar from '../components/NavBar'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Head from 'next/head'
import { HStack } from '@chakra-ui/react'
// Page template except for login/signup
export default function Layout({ children }) {
  return (
    <>
        <div className={styles.container}>
            <Head>
                <title>HowArt MunteSEO</title>
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        </div>

        <main>
            <NavBar />
            <HStack alignItems='top' spacing={0} minH='100vh'>
                <Sidebar />
                {children}
                <RightSidebar />
                
            </HStack>
            
        </main>

        {/* <footer className={styles.footer}>
            <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            >
            Powered by{' '}
            <span className={styles.logo}>
                <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
            </a>
        </footer> */}
    </>
  )
}